version: '3.1'
services:
  db-postgres:
    container_name: db-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_test
    ports: 
      - 5432:5432
    volumes: 
      - ./db-data:/var/lib/postgresql/data
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 5432:5432
